site_name: Entity Construction Kit
repo_url: https://github.com/systopia/de.systopia.eck
site_description: 'A guide for the EntityConstructionKit (eck).'
site_author: 'systopia'
theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Installation': installation.md
  - 'Adding Entities': adding-entities.md

markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en